### ISSUE TITLE
Release derelict-util commit as new version?

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [Zoadian/DerelictVulkan#6]
[My project](https://github.com/PolyplexEngine/libpp) depends on Derelict Util >= 3.0.0.
Is it possible that the commit could be put up as a new version on the dub database?

**Comment by SKY-13th** [comment]
Unfortunately, this question is not to me, but @Zoadian. He is owner of dub profile.

Currently, I can suggest you to include project to your dub file by adding a relative path to it, and add it as submodule to your repository.

**Comment by LunaTheFoxgirl** [comment]
My project is licensed as MIT, would that be ok to do?
Like is Boost and MIT compatible licenses? (I'm not a lawyer, licenses confuse me slightly)

**Comment by Lansatac** [comment]
My understanding is that Boost is fairly permissive and only requires notice, so you should be fine as long as you provide that. I'm not a lawyer either, so take that with a grain of salt.

**Comment by LunaTheFoxgirl** [comment]
Thanks @Zoadian! 👍
