### ISSUE TITLE
Cannot depend on xlib-d that depends on a different version of derelict-util

### ISSUE THREAD

**Issue by 0xEAB** [Zoadian/DerelictVulkan#7]
This library shouldn't depend on v3.0 of derelict-util, but v2.0...

```
Root package derelict-vulkan reference derelict-util >=3.0.0 cannot be satisfied.
Packages causing the conflict:
	xlib-d depends on ~>2.0.6
	derelict-vulkan depends on >=3.0.0
```

**Comment by SKY-13th** [comment]
Hello @0xEAB.

Yes, sorry about this one.
Actually, I found out about this issue recently, I just did not thought about it initially.

Fix it pretty simple, just to do same thing as been done with `Derelict-SDL2` binding about `SDL_SysWMinfo `: replace type dependency with corresponding `void*` for pointers or etc.

Unfortunately, I can't provide this fix right now (no suitable environment to test), but I will do it tomorrow, eventually.

Thank you for understanding.

**Comment by SKY-13th** [comment]
@0xEAB, Pull Request #8 has been submitted in `master` branch. 
It shout resolve the issue.

New version [`v0.0.20`](https://github.com/Zoadian/DerelictVulkan/tree/v0.0.20) will be available through `dub` in less then hour from release point (if believe [article](https://code.dlang.org/publish)).
For now `~master` can be used.

**Comment by 0xEAB** [comment]
Thank you :)
